### ISSUE TITLE
Consensus Messages

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-specs#126]
We need to define the messages that are exchanged by nodes during consensus. 

IMO, most of the messages defined by tendermint can be used and do not require any changes. The main change would be regarding the [BlockID](https://docs.tendermint.com/master/spec/core/data_structures.html#blockid) (which is used in [Votes](https://docs.tendermint.com/master/spec/core/data_structures.html#vote), [Proposal](https://docs.tendermint.com/master/spec/core/data_structures.html#proposal) etc).

Note that we also have a [BlockId](https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#blockid) in the ll-spec which is the hash of the header basically (differently from tendermint and still different from what would be required for validators s.t. can sample for DA proofs).

My understanding is that the Proposal should contain the data root at least. IMO, it should also contain the [DA header ](https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#availabledataheader) and the orig data square size. The last is optionally but it would simplify the implementation (and I don't see why it should not simply be included).

Happy to help with this as we need to define these for the implementation anyway!

**Comment by liamsi** [comment]
Here is a suggestion how it think the proposal should look like (in go syntax - the spec should contain it as a protobuf message):

```
type Proposal struct {
	// Fields required for tendermint consensus: 
	Type      SignedMsgType 
	Height    int64         
	Round     int32         
	PolRound  int32 
	// BlockID   becomes obsolete with the DA header included below
	// BlockID   BlockID
	Timestamp time.Time  
	Signature []byte

	// LazyLedger specific fields:

        // Necessary for "nodes to know how many chunks there are to sample from in advance"
        OriginalSquaresize uint32
        // Needed for nodes to sample DA proofs / retrieve the whole block if they want to.
        AvailableDataHeader  AvailableDataHeader      
}
```

https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#availabledataheader

**Comment by liamsi** [comment]
Note, `OriginalSquaresize ` is called `availableDataOriginalSharesUsed` in the spec and we need to clarify if we need to include the `AvailableDataHeader ` or if the `availableDataRoot` is sufficient. 

Copying over @adlerjohn's comment from discord:
> I think it should include any "extra" header fields we added that can't be inferred https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#header
> So, feeHeader.tipRate, and availableDataRoot. For performance we should probably include availableDataOriginalSharesUsed too.

**Comment by liamsi** [comment]
Originally I thought the `availableDataOriginalSharesUsed` is also necessary in the proposal but it is not. If the `AvailableDataHeader` is included, the original square size can be recomputed.

**Comment by liamsi** [comment]
@adlerjohn should keep the BlockID in the Proposal? And with BlockId I mean 
> The block ID is a single Merkle root: the root of the block header's fields, in the order provided in the spec. The root is computed using a binary Merkle tree.

**Comment by adlerjohn** [comment]
The block header consists of the following fields:

| name                              | type                      |
| --------------------------------- | ------------------------- |
| `height`                          | [Height](#type-aliases)   |
| `timestamp`                       | [Timestamp](#timestamp)   |
| `lastBlockID`                     | [BlockID](#blockid)       |
| `lastCommitHash`                  | [HashDigest](#hashdigest) |
| `consensusRoot`                   | [HashDigest](#hashdigest) |
| `feeHeader`                       | [FeeHeader](#feeheader)   |
| `stateCommitment`                 | [HashDigest](#hashdigest) |
| `availableDataOriginalSharesUsed` | `uint64`                  |
| `availableDataRoot`               | [HashDigest](#hashdigest) |
| `proposerAddress`                 | [Address](#address)       |

In addition to these, we should add a `round` field for consensus proposals, which is committed to in the Commit hash. While some fields can be optimized away since they can be inferred, it would probably be safer to keep them all in the proposal message as a kind of error checking. E.g. the `lastBlockID` can be omitted since there are no re-orgs...except if there are re-orgs (bugs, hard fork, etc.). The block ID of the current proposal can similarly be omitted, but there's no harm in including it, again as an error checking mechanism.

As for re-naming: I suggest either
1. Use the name `HeaderRoot`, since the block ID is the Merkle root of the header. This is inline with the rest of our re-naming (-hash for hashes, -root for roots). Or,
1. Hash the header instead of Merkleizing it. I actually recommend this path https://github.com/tendermint/spec/issues/175#issuecomment-701543731.

**Comment by liamsi** [comment]
> Validators should be expected to vote only when they've actually validated the whole block (all transactions + correct erasure coding), otherwise we lose the property that any invalid committed block will result in >=2/3 of stake being burned. 

What about the idea that validators can only decide to do data availability checks? Or at least only validate state transitions without downloading message data to verify the erasure coding? I think @musalbas feels strongly about this.

If validators have to download the whole block anyways, that would mean that we should actually keep the block gossiping routine (instead of having the validators that want to download the data pull it on demand from the network); ref: https://github.com/lazyledger/lazyledger-core/issues/85 and that would also be related to the ADR that @marbar3778 is working on. As far as I understood so far, forcing all validators to download all data was not an option?

> then have a sub-message type to fetch the full header, and the full available data header, and the full data

Sure, that is possible and closer to the current implementation (although everything is gossiped as parts currently - so one message type for everything). 

I think it alls boils down to the one question: what is the bare minimum of data a validator needs to vote on a block in LL. 

If everyone needs the DA header anyways, it should be part of the Proposal message. At least I do not see any good reason to send this in a separate message IMO (and fetch the DA header separately). It's certainly possible to have a separate message type for it though but it unnecessarily complicates reasoning about this. 

> (Also as an aside: without a signature from the proposer in the header/enforced in the Commit validation logic, how do we know for sure it was actually that validator that proposed the block?)

The signature is part of the proposal and the header. Oh, you mean if the validators don't have the header and only do sampling? 

I don't mind if the Header fields are merkelized or not. Both is good to me HeaderRoot or HeaderHash 👍🏼

**Comment by adlerjohn** [comment]
> What about the idea that validators can only decide to do data availability checks? Or at least only validate state transitions without downloading message data to verify the erasure coding?

I was kind of mangling a few different things with that line of thought. The two options I had in mind were:
1. Validators literally do nothing but vote on the header hash, validity and availability be damned. In that case, including the full available data header in the proposal is not necessary. We probably don't want this, so option 2:
1. Validators vote after doing at least DAS (I said full validation above but really it should just be DAS). In that case, you should probably include the full available data header in proposals. This option is fine.

**Comment by liamsi** [comment]
> No, I mean our Header struct only has proposer address, but no way of proving that that validator actually proposed the block in question.

Alright. That is also true for a vanilla tendermint Header. But the Proposal contains the proposer's signature. If >2/3 of validators signed the Proposal that should be proof enough? Is proving this later relevant for fraud proofs?  Or why should the proposer's sig be part of the header?

**Comment by adlerjohn** [comment]
> If >2/3 of validators signed the Proposal that should be proof enough that the proposer signed the proposal too?  Or why should the proposer's sig be part of the header?

Under an honest majority, yes. But if the majority of validators are dishonest, then you need to be able to hold them accountable. If they're going to be dishonest anyways, they can bring an honest validator down with them by blaming them for proposing the block. We can avoid this by requiring that the proposer must separately vote for the block, but then they should be distributing a `ConsensusVote` with their proposal, not a generic signature.

**Comment by liamsi** [comment]
> But if the majority of validators are dishonest, then you need to be able to hold them accountable. 

By whom and what consequences would that have?

> We can avoid this by requiring that the proposer must separately vote for the block, but then they should be distributing a ConsensusVote with their proposal, not a generic signature.

Not sure I'm following. The Proposal itself is a kind of Vote.

**Comment by adlerjohn** [comment]
> Accountable by whom and what consequences would that have?

Social consensus. I'm probably overthinking this, let me get back if I can come up with some concrete attack.

**Comment by liamsi** [comment]
The last few comments here about not assuming an honest majority assumption and falling back to social consensus could be interesting to discuss with @milosevic / the informal team. They spent a lot of time thinking about light-client attacks and it kinda feels related.
