### ISSUE TITLE
docs.lazyledger.org doesn't work

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-specs#133]
![image](https://user-images.githubusercontent.com/7441766/109839811-c7b54500-7c47-11eb-8e0e-ea7f8758923f.png)

**Comment by musalbas** [comment]
It's working fine, you just have to go to a sub-directory as there's no index page for /: https://docs.lazyledger.org/lazyledger-specs/

**Comment by liamsi** [comment]
Then this should be updated:

![image](https://user-images.githubusercontent.com/7441766/109843090-013b7f80-7c4b-11eb-8a9a-b6d55bf8ee57.png)

**Comment by musalbas** [comment]
Fixed.
