### ISSUE TITLE
Merkle tree default value deviates conceptually from RFC-6962

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-specs#57]
In  https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#binary-merkle-tree
we state:
> Binary Merkle trees are constructed in the same fashion as described in Certificate Transparency (RFC-6962). Leaves are hashed once to get leaf node values and internal node values are the hash of the concatenation of their children (either leaf nodes or other internal nodes).

but also

> The base case (an empty tree) is defined as zero:
node.v = 0x0000000000000000000000000000000000000000000000000000000000000000

This is confusing as we actually deviate from RFC-6962. There it says:
> The hash of an empty list is the hash of an empty string:
> MTH({}) = SHA-256().

https://tools.ietf.org/html/rfc6962#section-2.1

My understanding is that we only borrow how to split / try to balance the tree in case the leaf nums are odd. The base hasher and the base case are different.

**Comment by musalbas** [comment]
I think we should stick to RFC-6962 as a common standard, as these details don't matter much.

**Comment by liamsi** [comment]
I agree. I just think it should be clear where we deviate from it.

**Comment by adlerjohn** [comment]
Right, I should make the wording more precise here since it's not completely identical to RFC-6962.

**Comment by adlerjohn** [comment]
The decision is to stick closer to RFC-6962 for the root of an empty subtree, and use the hash of the empty string, i.e. `kaccak256()`.
