### ISSUE TITLE
Is removing validators and next validators' hashes absolutely necessary?

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-specs#65]
From a single abci app (in our case the state machine that tracks the minimal state necessary for PoS), it makes sense to remove these two hashes: https://github.com/tendermint/tendermint/blob/8571b2ee9a77ba62b24926324864677867e55124/types/block.go#L341-L342

They could be part of the appHash (stat root) anyways. My concern with this is that it does not make sense from the PoV of tendermint: they are essential information for tendermint consensus and these hashes are computed by tendermint (and not the app) which does not know or understand how the (abci) app deals with state. Also, the light client needs these two hashes (independent from how the app tacks state). This means we can't use most of the tendermint light client logic (which might be OK as the LL light client will be different enough anyways)

TODO: further discuss and clarify the implications of removing these two fields vs keeping them.

**Comment by adlerjohn** [comment]
Re-adding the next validators root in #75. One thing that's unclear is how this interacts with epochs. The Tendermint docs are a bit unclear on this, but I heard that validators are only actually changed once per epoch, instead of once per block? How does that work?

**Comment by liamsi** [comment]
Validators can change each block in Tendermint. I think Celo (?) and maybe other projects change validators every epoch.
