### ISSUE TITLE
Proofs shouldn't include the Merkle root or the value being proven, as this is part of the statement being proven, not the proof

### ISSUE THREAD

**Issue by musalbas** [lazyledger/lazyledger-specs#67]
>A Merkle proof is a proof for the statement "a key x has value y for the tree with root z". It doesn't make sense for the statement being proven to be a part of the proof, because the prover could always generate a valid proof if they get to pick the statement. Furthermore, the verifier may already know what the statement being proven is, so including it as part of the proof may be redundant. At minimum, they should already know what the root of the tree is.

See: https://github.com/lazyledger/smt/pull/5/files#r460376202

**Comment by liamsi** [comment]
Also, independent from including leaf and root, it is unclear what the current Namespace Merkle Tree Proofs are supposed to prove: 
https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#namespace-merkle-tree-proofs

Do they correspond to a single leaf inclusion proof? (seems like it as there is a single index/key of a leaf).

My understanding is that we need to kind of proofs:
 - whole namespace proofs
 - single leaf proofs 

Both can be implemented as range proofs.
