### ISSUE TITLE
erasure coding: square width should vary per block instead of being fixed

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-specs#68]
Currently, the `availableDataOriginalSquareSize` does not depend on the amount of data in the block if I understand correctly:
https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#consensus-parameters

What would be pros/cons to change this to depend on the amount of data in each block (and hence to vary per block)?

According to @adlerjohn:
>  But it could be made to vary per-block I guess. It would then need to be in the block header.

I think arranging the data into a square that depends on the total number of shares per block makes sense. Otherwise we might create large blocks for no reason.

**Comment by musalbas** [comment]
I think the size of the square definitely needs to be dynamic and not fixed, for security reasons. The lower the number of shares there are in a block, the more likely that all light clients will have collectively sampled them. Furthermore, having a fixed square size would mean that nodes need to do an amount of computation equivalent to the maximum block size to compute the root every time, which is very inefficient.

**Comment by adlerjohn** [comment]
Makes sense to have it vary per block.

**Comment by liamsi** [comment]
OK, seems like we all agree that this should vary per block. Updated the title and the labels to better reflect this decision.
