### ISSUE TITLE
Splitting into shares needs to know request length

### ISSUE THREAD

**Issue by adlerjohn** [lazyledger/lazyledger-specs#69]
Currently [shares](https://github.com/lazyledger/lazyledger-specs/blob/7e35c6bbbee59b8e687c94c8483a550d7e68d330/specs/data_structures.md#share) for transactions, evidence, and intermediate state roots are [arranged](https://github.com/lazyledger/lazyledger-specs/blob/7e35c6bbbee59b8e687c94c8483a550d7e68d330/specs/data_structures.md#arranging-available-data-into-shares) by first serializing an array of e.g. transactions, then splitting them into 255-byte shares (with the 256th byte reserved to indicate the starting location of the first start of a transaction in the share.

The issue here is that simply serializing an array of transactions doesn't return the length of each serialized transaction, so we can't properly compute the reserved byte value.

Splitting into shares should instead use the following procedure:
1. Serialize each transaction _individually_ (which tells us the number of bytes for each transaction)
1. Create the byte array `serialize(length of serialize(tx1)) || serialize(tx1) || serialize(length of serialize(tx2)) || serialize(tx2) || ...`
1. Split the above byte array into 255-byte shares, and use the lengths from step (1) to compute reserved byte values

**Comment by liamsi** [comment]
using protobuf this can be achieved without any manual implementation (at least in most languages):
https://developers.google.com/protocol-buffers/docs/techniques#streaming

Otherwise this is simple enough to implement in any language.

**Comment by liamsi** [comment]
Two remarks here:

In 1. the individual serialzation of a TX does it include the lengths or not? Let's say Tx1 is 300 bytes of encoding, then 2. gives us:
`serialize(length of serialize(tx1)) || serialize(tx1) || serialize(length of serialize(tx2)) || serialize(tx2)`
So, If we split it up in 3. do the reserved byte value tell us where `serialize(length of serialize(tx2))` starts, or, where `serialize(tx2)` starts?

**Comment by adlerjohn** [comment]
The reserved byte should tell us where `serialize(length of serialize(tx2))` starts, otherwise we wouldn't know how many bytes to use to decode a tx.

> the computed lengths also include the length delimiter overhead

I don't think that's needed? The length is always a single integer, so a transaction can be parsed in two steps (first parse the length starting at the right offset, then parse the next length bytes as a tx).

**Comment by liamsi** [comment]
OK, I think you are right.
