### ISSUE TITLE
Block proposer

### ISSUE THREAD

**Issue by marbar3778** [lazyledger/lazyledger-specs#72]
Honest block proposer link in block_proposer.md is local host. 😄 

http://localhost/#honest-block-proposer

**Comment by liamsi** [comment]
Where exactly?
![image](https://user-images.githubusercontent.com/7441766/94473450-7e5e5680-01cc-11eb-99af-f750b37414ed.png)

**Comment by marbar3778** [comment]
Same for wire format link in networking.md.

Todos or not providing a link may be better?

**Comment by marbar3778** [comment]
Ah whoops I'm on an iPad and I guess GitHub injects localhost

**Comment by adlerjohn** [comment]
Those top-level links need to be removed anyways, they're there from the old ToC auto-generator settings.
