### ISSUE TITLE
Get rid of compromises made to be closer to tendermint implementation (where it makes sense)

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-specs#78]
It often seems like a good trade-off to keep some details that originated from the way tendermint (and abci) is designed in the spec. We've now decided that we draw the line to were we want to avoid this at (almost) all costs were we have to make trade-offs that are consensus-critical:

> when it comes to things like data structures etc [the spec] should be designed according to the Tendermint implementation
> But we shouldn't have to make consensus-critical trade-offs due to the Tendermint implementation, like adding extra fraud proofs

Potentially incomplete list of fields that are artefacts from the way tendermint / abci is designed which we would not include in an ideal LL spec: `ValidatorsHash`, `NextValidatorsHash`. 

While this could mean that the implementation could incrementally be made safe while we remove implementation specific details step by step, we have to make sure that the spec is sane and specifies a safe system.

ref: https://github.com/lazyledger/lazyledger-specs/pull/75
ref: https://github.com/lazyledger/lazyledger-specs/issues/65

**Comment by adlerjohn** [comment]
Closing in favor of medium-term decision to compromise unless strictly necessary for security or significant performance.
