### ISSUE TITLE
Specify cryptographic primitives

### ISSUE THREAD

**Issue by Liamsi** [LazyLedger/lazyledger-specs#8]
LazyLedger, as all blockchains uses numerous cryptographic primitives (most notably, hash functions and ecdsa or other cryptographic signature algorithms, e.g. BLS). 
We need to choose among these and document the choices made in the spec (and ideally document why these decisions where made somewhere else). 

Note: While these decisions are critical for a final spec, decisions about well established building blocks can happen at a later point in time in the specification process. We can and should start the implementation with the choices made in tendermint anyways to rapidly prototype.

**Comment by adlerjohn** [comment]
Reopening since we need to more completely define the signature scheme, and how it interacts with consensus messages (e.g. votes).
