### ISSUE TITLE
Investigate square sizes that aren't a power of 2

### ISSUE THREAD

**Issue by adlerjohn** [lazyledger/lazyledger-specs#80]
#79 made the size of the available data square variable per block (with a fixed maximum size). It (and the rest of the pre-existing rationale) assumes that the current square size is a power of 2, however [this is not strictly necessary](https://github.com/lazyledger/lazyledger-specs/pull/79#discussion_r502630119).

We should investigate what complexities that are introduced by allowing arbitrary square sizes (upper bounded by the maximum), and if acceptable, propose an algorithm for determining the structure of commitments to available data that is required for transactions.

**Comment by adlerjohn** [comment]
Allowing square sizes that aren't a square of 2 could mean both less compute work to do the erasure coding, and smaller commitments to the available data. However, the FFTs used in RS erasure coding apparently are most efficient when the underlying data is exactly a power of 2. Moreover, the performance apparently gets worse the larger the prime factors of the underlying data.

In order to determine if this applies to our situation, we'll need to run some experiments with [leopard](https://github.com/catid/leopard).

Note that even with square sizes as a power of 2, rows that only consist of tail padding (zeroes after all messages) don't actually need to be committed to, _or sampled_.

**Comment by adlerjohn** [comment]
Upon further investigation, leopard doesn't perform erasure coding on an arbitrary number of shares, but instead zero-pads to the smallest power of 2 that's at least as large. This can be seen in the memory layout figure [here](https://github.com/catid/leopard#online-calculations) (transcluded below for posterity). In other words, I can't even run any experiments without making enormous changes to leopard. I'm sure there's a good reason for padding to a power of 2, probably the ones listed above.

```
[Recovery Data (Power of Two = M)] [Original Data (K)] [Zero Padding out to N]
```

With that in mind, allowing non-power-of-2 square sizes is probably not something we want to do. That being said, we can reduce the "waste" of power-of-2 square sizes by adding a field to the block header for the number of shares before [tail padding](https://github.com/lazyledger/lazyledger-specs/blob/0c7b4ba70860e9ae7da55a9837deb8842519f391/specs/consensus.md#reserved-namespace-ids). Any shares after that are implicitly known, and thus available, so they don't need to be sampled, and rows containing only tail padding don't need to be committed to.

**Comment by liamsi** [comment]
Just noting that original data (K) is what is fed into the leopard lib which doesn't need to be a power of two. Internally, the mem-layout will be zero-padded to a power of 2 which will be >= M + K. Hence I said it can be used with any number of shares as long as those are split into multiples of 64. Not sure what experiments you were trying to run but at least you can feed any number of shares into leopard. 

> That being said, we can reduce the "waste" of power-of-2 square sizes by adding a field to the block header for the number of shares before tail padding. Any shares after that are implicitly known, and thus available, so they don't need to be sampled, and rows containing only tail padding don't need to be committed to.

That sounds good to me 👌
