### ISSUE TITLE
Investigate different fee mechanisms

### ISSUE THREAD

**Issue by adlerjohn** [lazyledger/lazyledger-specs#82]
This issue tracks alternatives for fee mechanisms, [that were brought up in](https://github.com/lazyledger/lazyledger-specs/pull/79#issuecomment-706302260) #79.

**Comment by liamsi** [comment]
Ideally there should be a fee market for Tx (including messages) that solely depend on supply and demand.

Depending on the demand, validators, are free to include messages that aren't payed for and are not even tied to any account. These messages should always have lower (lowest) priority in the mempool. If the mempool is full incoming messages with no account will simply be dropped. If there is a lot of free capacity, free messages can be included (but there is no guarantee obviously and validator-nodes could be configured to have a minimal fee of course). 

Not sure if allowing to allow Messages with no Tx (or with no account) is actually feasible or that important. But we should consider if we want to make this hard requirement or not.

**Comment by liamsi** [comment]
Was this closed accidentally? If not, which PR did resolve it?

**Comment by adlerjohn** [comment]
This was resolved with #96. If we want to further investigate fee mechanisms we can re-open, but for now it's not on the radar any more.
