### ISSUE TITLE
Padding shares should be deterministic and consensus-enforced

### ISSUE THREAD

**Issue by adlerjohn** [lazyledger/lazyledger-specs#86]
[Currently](https://github.com/lazyledger/lazyledger-specs/blob/301b88ecfeb0953a97e4f349729deded01a5364f/specs/data_structures.md#arranging-available-data-into-shares), padding between messages can have any namespace ID between the namespace IDs of the surrounding messages:
> The non-interactive default rules may introduce empty shares that do not belong to any message (in the example above, the top-right share is empty). These must be explicitly disclaimed by the block producer using special transactions.

However, these padding shares aren't included when distributing the entire block all at once, since blocks aren't distributed normally laid out as shares. To fix this, the namespace ID of padding shares must be both deterministic and enforced by consensus.

**Comment by adlerjohn** [comment]
Idea: the issue with allowing padding shares to be for any namespace ID between surrounding messages _inclusive_ is that range proofs could end up having a bunch of useless shares, The solution is simple: restrict "real" shares to even namespace IDs and padding to odd namespace IDs (or vice versa).

**Comment by liamsi** [comment]
That would mean apps can only have even namespace IDs, right? That also means all odd namespaced messages will have to be rejected?
Also, even and odd are a bit ambiguous (nids are just bytes as far as I remember) but i guess that will be specified further in the corresponding PR.

**Comment by adlerjohn** [comment]
> That would mean apps can only have even namespace IDs, right?

Yes. So instead of the current 64 bits, apps would have 63 bits for namespaces (oh noes).

> That also means all messages with odd namespace IDs will have to be rejected?

Yes. Or rather, transactions that pay for a message with an odd namespace ID would be invalid. Which is trivial to enforce.

> even and odd are a bit ambiguous (nids are just bytes...)

True, they're currently byte arrays instead of an int. The PR should use "lowest bit 0/1" instead.

**Comment by adlerjohn** [comment]
Actually, upon further consideration this is both a terrible idea and not needed. The first because this prevents two messages with the same namespace ID from being included unless they perfectly line up, and the second because the transactions that pay for messages already provide this information.
