### ISSUE TITLE
Decide on data model for validator set

### ISSUE THREAD

**Issue by adlerjohn** [lazyledger/lazyledger-specs#9]
There are two viable data models that we need to choose between for the validator set and fee-paying account balances: UTXOs and accounts. Defining a transaction format is dependent on this.

## Considerations

Transactions are generally larger in the UTXO data model, and reasoning about a single account receiving funds is more complex. However, it allows for easier parallel validation and, most importantly, it more conducive for HTLCs (which can be used for cross-chain atomic swaps without execution---an indispensable feature).

## Recommendation

Given that there will be no repeated interactions with contracts, the UTXO data model looks preferable.

**Comment by Liamsi** [comment]
Note that in tendermint, validator set changes happen via abci and tendermint (and with it lazyledger-core) does not know how the tendermint-app tracks this kind of state. Wich is neat as we can choose whatever we want. 

That said, the SDK assumes the account model in quite some places. From an implementation PoV, do you see any major downside if we've started a prototype with an account model and switch to UTXO later?

Also, could you briefly explain this:

> Given that there will be no repeated interactions with contracts

**Comment by adlerjohn** [comment]
There shouldn't be any inherent issues to prototyping with an accounts data model first. Fraud proofs and state representation should remain largely the same. The biggest change needed would be to the transaction format.

> Also, could you briefly explain this

The primary benefit of the accounts data model (other than potential space savings) is contract interaction, i.e. it makes it easier for a contract to know that two calls are from the same or different accounts. There are no contracts on LazyLedger, so this advantage isn't useful for us.

**Comment by adlerjohn** [comment]
The accounts data model will be used for now.
